### PR TITLE
add popup with button to trigger auth

### PR DESCRIPTION
**Pull request by gburning**
- [x] popup with button to auth extension
- [ ] way to revoke auth (schmaybe just clear out the stored token?)

### CODE REVIEW

**Comment by gburning** [comment]
@Karagath I added a bundler (Rollup) and re-structured some things. But I'm not completely sure that it works as it should.

**Review by Karagath — CHANGES_REQUESTED** [review]
There are a few files that would benefit from a newline at eof

**Comment by Karagath** [comment]
looks good

**Comment by Karagath** [comment]
What may not work in rollup?

**Review by Karagath — APPROVED** [review]

**Pull request merged**
